### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by Kuldebar** [Kuldebar/The-Classical-World#4]
- Cartography cost will be dramatically increased.

- Public Works needs relook

- additional techs to be added

- separate modules: Wonders, Civs, Buildings, Policies...buildings to complement Classical World Tech Tree will likely be made into a separate module which will include Classical Harbor/Shipyard for starters.

- Civ leader revamp:

Hamilcar I of Carthage, Justinian I of Byzantine, Vercingetorix the Gaul of Celts,  Pericles of Greece....

- Old World Map as out of box "official map"

![baa6c32ad04790a137df29ce24e2b36c.jpeg](https://user-images.githubusercontent.com/117689753/206923503-1059d7f7-dcce-4e59-955d-a4bd9df103a6.jpeg)

- Maritime units upgrades, galley relook

**Comment by Dimensiondog** [comment]
Personally i'd make the old world map's southern border at just below india for either a smaller map or more detailled one.

**Comment by Kuldebar** [comment]
> Personally i'd make the old world map's southern border at just below india for either a smaller map or more detailled one.

Your right, I'll be making a variation of the Mela Map which includes India and China but drastically condensed. Hoping to get enough details in at the expense of modern geographical sensibilities, although with north up instead of east.

https://vividmaps.com/map-ancient-roman-world-perspective/

**Comment by Kuldebar** [comment]
The the tech tree portion is mostly complete. Policies and Beliefs are next because they will be part of this module of the Classical World project.
